#lang info
(define collection "rkt-ollama")
(define deps '("base" "expeditor-lib"))
(define build-deps '())
(define scribblings '())
(define pkg-desc "simple ollama repl for terminal or drracket")
(define version "0.0")
(define pkg-authors '(yjqww6))
(define license '(Apache-2.0 OR MIT))
(define compile-omit-paths '("examples"))
